#!/usr/bin/perl
#Sept.27,2010 by Terri Porter
#Script to grab just the seed fasta from the fasta file generated by uclust2fasta.  Then use the seedfasta to get the fasta stats for dereplicated dataset.
#usage $perl grab_seed_fasta.plx < results.fasta > results_seed.fasta

use strict;
use warnings;

#declare variables
my $line;
my $flag1=0;
my $flag2=0;

while (<>) {
	$line = $_;
	chomp $line;
	if ($line =~ /\*/) {
		print "$line\n";
		$flag1 = 1;
		$flag2 = 0;
	}
	elsif ($flag1 == 1) {
		print "$line\n";
		$flag1=0;
		$flag2 = 1;
	}
	elsif ($flag2 == 1) {
		next;
	}
}

