#!/usr/bin/perl
#Terri Porter, Jan. 15, 2013
#Script to use a list of orthoids, and grab only these sequenes from SP.fasta and AB.fasta generated by parse_out_Sp.plx
#orthoids need to be in a vertical list
#Also use this opportunity to remove all "-" gaps
#perl grab_seqs_of_interest.plx orthoids_of_interest.txt file.fasta

use strict;
use warnings;

#declare var
my $i=0;
my $line;
my $seq;
my $orthoId;

#declare array
my @ortho;
my @fasta;

#declare hash
my %orthoId_seq;

open (ORTHO, "<", $ARGV[0]) || die "Error cannot read ortho list: $!\n";
@ortho = <ORTHO>;
close ORTHO;

open (FASTA, "<", $ARGV[1]) || die "Error cannot read fasta file: $!\n";
@fasta = <FASTA>;
close FASTA;

#hash the fasta file
while ($fasta[$i]) {
		$line = $fasta[$i];
		chomp $line;

		if ($line =~ /^>/) {
			$line =~ /^>(\d+)/;
			$orthoId = $1;
		}
		elsif ($line !~ /^>/) {
			$line =~ s/-//g;
			$seq = $line;
			$orthoId_seq{$orthoId} = $seq;
			$orthoId=();
			$seq=();
		}
		$i++;
		$line=();
	}
$i=0;

#grab just the seqs of interest
open (OUT, ">>", "out.fasta") || die "Error cannot open outfile: $!\n";

while ($ortho[$i]) {
	$orthoId=$ortho[$i];
	chomp $orthoId;

	if (exists $orthoId_seq{$orthoId}) {
		$seq = $orthoId_seq{$orthoId};
		print OUT ">$orthoId\n$seq\n";
	}
	$i++;
}
$i=0;
close OUT;	



